import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/headeriamshenyc";
import HeaderMobile from "@/components/header-mobileiamshenyc";
import SideNav from "@/components/side-naviamshenyc";
import PageWrapper from "@/components/page-wrapperiamshenyc";
import MarginWidthWrapper from "@/components/margin-width-wrapperiamshenyc";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body className={`bg-black${inter.className}`}>
                <SideNav />
                <div className="flex">
                    <main className="flex-1">
                        <MarginWidthWrapper>
                            <Header />
                            <HeaderMobile />
                            <PageWrapper>{children}</PageWrapper>
                        </MarginWidthWrapper>
                    </main>
                </div>
            </body>
        </html>
    );
}
